"""community_initial

Revision ID: d77b9ff3fa28
Revises: 
Create Date: 2026-03-01 18:29:45.475534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd77b9ff3fa28'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_configurations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('organization_name', sa.String(length=200), nullable=False),
    sa.Column('organization_logo_url', sa.String(length=500), nullable=True),
    sa.Column('organization_description', sa.Text(), nullable=True),
    sa.Column('organization_reference_url', sa.String(length=500), nullable=True),
    sa.Column('organization_keywords', sa.Text(), nullable=True),
    sa.Column('default_exercise_duration_hours', sa.Integer(), nullable=False),
    sa.Column('default_time_multiplier', sa.Integer(), nullable=False),
    sa.Column('default_maturity_level', sa.String(length=20), nullable=False),
    sa.Column('default_exercise_mode', sa.String(length=20), nullable=False),
    sa.Column('enable_tv_plugin', sa.Boolean(), nullable=False),
    sa.Column('enable_social_plugin', sa.Boolean(), nullable=False),
    sa.Column('enable_welcome_kits', sa.Boolean(), nullable=False),
    sa.Column('enable_scoring', sa.Boolean(), nullable=False),
    sa.Column('session_timeout_minutes', sa.Integer(), nullable=False),
    sa.Column('max_login_attempts', sa.Integer(), nullable=False),
    sa.Column('password_min_length', sa.Integer(), nullable=False),
    sa.Column('smtp_enabled', sa.Boolean(), nullable=False),
    sa.Column('smtp_host', sa.String(length=255), nullable=True),
    sa.Column('smtp_port', sa.Integer(), nullable=True),
    sa.Column('smtp_user', sa.String(length=255), nullable=True),
    sa.Column('smtp_from', sa.String(length=255), nullable=True),
    sa.Column('simulator_inject_mapping', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_app_configurations'))
    )
    op.create_table('plugin_configurations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('plugin_type', postgresql.ENUM('directory', 'social_internal', 'social_network', 'tv', 'mailbox', 'email', 'chat', 'press_feed', 'sms', 'gov_channel', 'anssi_channel', 'DIRECTORY', 'SOCIAL_INTERNAL', 'SOCIAL_NETWORK', 'TV', 'MAILBOX', 'EMAIL', 'CHAT', 'PRESS_FEED', 'SMS', 'GOV_CHANNEL', 'ANSSI_CHANNEL', name='plugin_type'), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=False),
    sa.Column('color', sa.String(length=30), nullable=False),
    sa.Column('default_enabled', sa.Boolean(), nullable=False),
    sa.Column('coming_soon', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plugin_configurations')),
    sa.UniqueConstraint('plugin_type', name='uq_plugin_config_type'),
    sa.UniqueConstraint('plugin_type', name=op.f('uq_plugin_configurations_plugin_type'))
    )
    op.create_table('tenants',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('slug', sa.String(length=63), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'SUSPENDED', 'ARCHIVED', name='tenantstatus'), nullable=False),
    sa.Column('primary_domain', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tenants'))
    )
    op.create_index(op.f('ix_tenants_slug'), 'tenants', ['slug'], unique=True)
    op.create_table('teams',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_teams_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_teams'))
    )
    op.create_index(op.f('ix_teams_tenant_id'), 'teams', ['tenant_id'], unique=False)
    op.create_table('tenant_configurations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('organization_name', sa.String(length=200), nullable=False),
    sa.Column('organization_logo_url', sa.String(length=500), nullable=True),
    sa.Column('organization_description', sa.Text(), nullable=True),
    sa.Column('organization_reference_url', sa.String(length=500), nullable=True),
    sa.Column('organization_keywords', sa.Text(), nullable=True),
    sa.Column('legacy_app_config_overrides', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_tenant_configurations_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tenant_configurations')),
    sa.UniqueConstraint('tenant_id', name='uq_tenant_configurations_tenant_id')
    )
    op.create_index(op.f('ix_tenant_configurations_tenant_id'), 'tenant_configurations', ['tenant_id'], unique=False)
    op.create_table('tenant_domains',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('domain_type', sa.Enum('SUBDOMAIN', 'CUSTOM', name='tenantdomaintype'), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_tenant_domains_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tenant_domains')),
    sa.UniqueConstraint('domain', name='uq_tenant_domains_domain')
    )
    op.create_index(op.f('ix_tenant_domains_tenant_id'), 'tenant_domains', ['tenant_id'], unique=False)
    op.create_table('tenant_plugin_configurations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('plugin_type', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('color', sa.String(length=30), nullable=True),
    sa.Column('default_enabled', sa.Boolean(), nullable=True),
    sa.Column('coming_soon', sa.Boolean(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_tenant_plugin_configurations_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tenant_plugin_configurations')),
    sa.UniqueConstraint('tenant_id', 'plugin_type', name='uq_tenant_plugin_config_tenant_plugin')
    )
    op.create_index(op.f('ix_tenant_plugin_configurations_tenant_id'), 'tenant_plugin_configurations', ['tenant_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', 'animateur', 'observateur', 'participant', name='user_role'), nullable=False),
    sa.Column('is_platform_admin', sa.Boolean(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('avatar_url', sa.String(length=512), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_users_team_id_teams'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_users_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('tenant_id', 'email', name='uq_users_tenant_email'),
    sa.UniqueConstraint('tenant_id', 'username', name='uq_users_tenant_username')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_index(op.f('ix_users_team_id'), 'users', ['team_id'], unique=False)
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('old_values', sa.JSON(), nullable=True),
    sa.Column('new_values', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_audit_log_tenant_id_tenants'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_audit_log_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log'))
    )
    op.create_index(op.f('ix_audit_log_action'), 'audit_log', ['action'], unique=False)
    op.create_index(op.f('ix_audit_log_created_at'), 'audit_log', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_log_tenant_id'), 'audit_log', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_audit_log_user_id'), 'audit_log', ['user_id'], unique=False)
    op.create_table('exercises',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'running', 'paused', 'completed', 'archived', name='exercise_status'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('time_multiplier', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('exercise_type', sa.Enum('CYBER', 'IT_OUTAGE', 'RANSOMWARE', 'MIXED', name='exercisetype'), nullable=False),
    sa.Column('target_duration_hours', sa.Integer(), nullable=False),
    sa.Column('maturity_level', sa.Enum('BEGINNER', 'INTERMEDIATE', 'EXPERT', name='exercisematuritylevel'), nullable=False),
    sa.Column('mode', sa.Enum('REAL_TIME', 'COMPRESSED', 'SIMULATED', name='exercisemode'), nullable=False),
    sa.Column('planned_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('location', sa.String(length=500), nullable=True),
    sa.Column('business_objective', sa.Text(), nullable=True),
    sa.Column('technical_objective', sa.Text(), nullable=True),
    sa.Column('lead_organizer_user_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_exercises_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lead_organizer_user_id'], ['users.id'], name=op.f('fk_exercises_lead_organizer_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_exercises_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exercises'))
    )
    op.create_index(op.f('ix_exercises_tenant_id'), 'exercises', ['tenant_id'], unique=False)
    op.create_table('inject_bank_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('owner_tenant_id', sa.Integer(), nullable=True),
    sa.Column('custom_id', sa.String(length=100), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('kind', sa.Enum('idea', 'video', 'audio', 'scenario', 'chronogram', 'image', 'mail', 'message', 'directory', 'reference_url', 'social_post', 'document', 'canal_press', 'canal_anssi', 'canal_gouvernement', 'other', name='injectbankkind'), nullable=False),
    sa.Column('status', sa.Enum('draft', 'ready', 'archived', name='injectbankstatus'), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('data_format', sa.String(length=16), server_default='text', nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('visibility_scope', sa.Enum('PRIVATE', 'TENANT', 'SHARED', name='injectbankvisibilityscope'), nullable=False),
    sa.Column('shareable', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('source_type', sa.Enum('TENANT', 'PLATFORM', name='injectbankitemsourcetype'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_inject_bank_items_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_tenant_id'], ['tenants.id'], name=op.f('fk_inject_bank_items_owner_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inject_bank_items'))
    )
    op.create_index(op.f('ix_inject_bank_items_category'), 'inject_bank_items', ['category'], unique=False)
    op.create_index(op.f('ix_inject_bank_items_custom_id'), 'inject_bank_items', ['custom_id'], unique=True)
    op.create_index(op.f('ix_inject_bank_items_kind'), 'inject_bank_items', ['kind'], unique=False)
    op.create_index(op.f('ix_inject_bank_items_owner_tenant_id'), 'inject_bank_items', ['owner_tenant_id'], unique=False)
    op.create_index(op.f('ix_inject_bank_items_source_type'), 'inject_bank_items', ['source_type'], unique=False)
    op.create_index(op.f('ix_inject_bank_items_status'), 'inject_bank_items', ['status'], unique=False)
    op.create_index(op.f('ix_inject_bank_items_visibility_scope'), 'inject_bank_items', ['visibility_scope'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('session_scope', sa.String(length=20), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_sessions_tenant_id_tenants'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sessions'))
    )
    op.create_index(op.f('ix_sessions_expires_at'), 'sessions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_sessions_tenant_id'), 'sessions', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_sessions_token_hash'), 'sessions', ['token_hash'], unique=True)
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_table('user_teams',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('is_leader', sa.Boolean(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_user_teams_team_id_teams'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_teams_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'team_id', name=op.f('pk_user_teams'))
    )
    op.create_table('welcome_kit_templates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('kind', sa.Enum('PLAYER', 'FACILITATOR', name='welcomekitkind'), nullable=False),
    sa.Column('template_markdown', sa.Text(), nullable=False),
    sa.Column('variables', sa.JSON(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_welcome_kit_templates_created_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_welcome_kit_templates'))
    )
    op.create_table('crisis_contacts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('function', sa.String(length=200), nullable=True),
    sa.Column('organization', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('mobile', sa.String(length=50), nullable=True),
    sa.Column('category', sa.Enum('AUTORITE', 'EXPERT', 'MEDIA', 'INTERNE', 'EXTERNE', 'URGENCE', 'AUTRE', name='contactcategory'), nullable=False),
    sa.Column('priority', sa.Enum('CRITICAL', 'HIGH', 'NORMAL', 'LOW', name='contactpriority'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('availability', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], name=op.f('fk_crisis_contacts_exercise_id_exercises'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_crisis_contacts'))
    )
    op.create_index('ix_crisis_contacts_category', 'crisis_contacts', ['exercise_id', 'category'], unique=False)
    op.create_index(op.f('ix_crisis_contacts_exercise_id'), 'crisis_contacts', ['exercise_id'], unique=False)
    op.create_index('ix_crisis_contacts_exercise_search', 'crisis_contacts', ['exercise_id', 'name', 'organization'], unique=False)
    op.create_table('decisions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('impact', sa.Text(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], name=op.f('fk_decisions_exercise_id_exercises'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_decisions_team_id_teams'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_decisions_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_decisions'))
    )
    op.create_index(op.f('ix_decisions_exercise_id'), 'decisions', ['exercise_id'], unique=False)
    op.create_index(op.f('ix_decisions_team_id'), 'decisions', ['team_id'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('EXERCISE_CREATED', 'EXERCISE_STARTED', 'EXERCISE_PAUSED', 'EXERCISE_ENDED', 'INJECT_CREATED', 'INJECT_SCHEDULED', 'INJECT_SENT', 'INJECT_CANCELLED', 'MAIL_DELIVERED', 'MAIL_OPENED', 'MAIL_REPLIED', 'TWITTER_POSTED', 'TWITTER_REPLY', 'TWITTER_VIRAL', 'TV_SEGMENT_STARTED', 'TV_SEGMENT_ENDED', 'TV_BANNER_CHANGED', 'DECISION_LOGGED', 'SCORE_ADDED', 'NOTE_ADDED', 'MEDIA_UPLOADED', 'USER_JOINED', 'USER_REACTION', name='eventtype'), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('actor_type', sa.Enum('USER', 'ACTOR', 'SYSTEM', 'AUTOMATION', name='eventactortype'), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('actor_label', sa.String(length=100), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('ts', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('exercise_time', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_events_actor_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], name=op.f('fk_events_exercise_id_exercises'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_events'))
    )
    op.create_index('ix_events_entity', 'events', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_events_exercise_id'), 'events', ['exercise_id'], unique=False)
    op.create_index('ix_events_exercise_ts', 'events', ['exercise_id', 'ts'], unique=False)
    op.create_index(op.f('ix_events_ts'), 'events', ['ts'], unique=False)
    op.create_table('exercise_escalation_axes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('axis_type', sa.Enum('TECHNICAL', 'COMMUNICATION', 'LEGAL', 'POLITICAL', 'MEDIA', name='escalationaxistype'), nullable=False),
    sa.Column('intensity', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], name=op.f('fk_exercise_escalation_axes_exercise_id_exercises'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exercise_escalation_axes'))
    )
    op.create_index(op.f('ix_exercise_escalation_axes_exercise_id'), 'exercise_escalation_axes', ['exercise_id'], unique=False)
    op.create_table('exercise_metric_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('stress', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('saturation', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('communication_external', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('technical_mastery', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], name=op.f('fk_exercise_metric_snapshots_exercise_id_exercises'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exercise_metric_snapshots'))
    )
    op.create_index(op.f('ix_exercise_metric_snapshots_exercise_id'), 'exercise_metric_snapshots', ['exercise_id'], unique=False)
    op.create_index(op.f('ix_exercise_metric_snapshots_ts'), 'exercise_metric_snapshots', ['ts'], unique=False)
    op.create_table('exercise_phases',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('phase_order', sa.Integer(), nullable=False),
    sa.Column('start_offset_min', sa.Integer(), nullable=True),
    sa.Column('end_offset_min', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], name=op.f('fk_exercise_phases_exercise_id_exercises'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exercise_phases')),
    sa.UniqueConstraint('exercise_id', 'phase_order', name='uq_exercise_phase_order')
    )
    op.create_index(op.f('ix_exercise_phases_exercise_id'), 'exercise_phases', ['exercise_id'], unique=False)
    op.create_table('exercise_plugins',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('plugin_type', postgresql.ENUM('directory', 'social_internal', 'social_network', 'tv', 'mailbox', 'email', 'chat', 'press_feed', 'sms', 'gov_channel', 'anssi_channel', 'DIRECTORY', 'SOCIAL_INTERNAL', 'SOCIAL_NETWORK', 'TV', 'MAILBOX', 'EMAIL', 'CHAT', 'PRESS_FEED', 'SMS', 'GOV_CHANNEL', 'ANSSI_CHANNEL', name='plugin_type'), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('configuration', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], name=op.f('fk_exercise_plugins_exercise_id_exercises'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exercise_plugins')),
    sa.UniqueConstraint('exercise_id', 'plugin_type', name='uq_exercise_plugins_exercise_type')
    )
    op.create_index(op.f('ix_exercise_plugins_exercise_id'), 'exercise_plugins', ['exercise_id'], unique=False)
    op.create_table('exercise_scenarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('strategic_intent', sa.Text(), nullable=True),
    sa.Column('initial_context', sa.Text(), nullable=True),
    sa.Column('initial_situation', sa.Text(), nullable=True),
    sa.Column('implicit_hypotheses', sa.Text(), nullable=True),
    sa.Column('hidden_brief', sa.Text(), nullable=True),
    sa.Column('pedagogical_objectives', sa.JSON(), nullable=True),
    sa.Column('evaluation_criteria', sa.JSON(), nullable=True),
    sa.Column('stress_factors', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], name=op.f('fk_exercise_scenarios_exercise_id_exercises'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exercise_scenarios'))
    )
    op.create_index(op.f('ix_exercise_scenarios_exercise_id'), 'exercise_scenarios', ['exercise_id'], unique=True)
    op.create_table('exercise_teams',
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], name=op.f('fk_exercise_teams_exercise_id_exercises'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_exercise_teams_team_id_teams'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('exercise_id', 'team_id', name=op.f('pk_exercise_teams'))
    )
    op.create_table('exercise_user_credentials',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('plain_password', sa.String(length=100), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], name=op.f('fk_exercise_user_credentials_exercise_id_exercises'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_exercise_user_credentials_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exercise_user_credentials'))
    )
    op.create_table('exercise_users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('ANIMATEUR', 'OBSERVATEUR', 'JOUEUR', name='exerciserole'), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('organization', sa.String(length=255), nullable=True),
    sa.Column('real_function', sa.String(length=255), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('assigned_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], name=op.f('fk_exercise_users_assigned_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], name=op.f('fk_exercise_users_exercise_id_exercises'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_exercise_users_team_id_teams'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_exercise_users_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exercise_users')),
    sa.UniqueConstraint('user_id', 'exercise_id', name='uq_user_exercise')
    )
    op.create_index(op.f('ix_exercise_users_exercise_id'), 'exercise_users', ['exercise_id'], unique=False)
    op.create_index(op.f('ix_exercise_users_user_id'), 'exercise_users', ['user_id'], unique=False)
    op.create_table('inject_bank_share_grants',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('source_tenant_id', sa.Integer(), nullable=False),
    sa.Column('target_tenant_id', sa.Integer(), nullable=False),
    sa.Column('access_mode', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_inject_bank_share_grants_created_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['item_id'], ['inject_bank_items.id'], name=op.f('fk_inject_bank_share_grants_item_id_inject_bank_items'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_tenant_id'], ['tenants.id'], name=op.f('fk_inject_bank_share_grants_source_tenant_id_tenants'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_tenant_id'], ['tenants.id'], name=op.f('fk_inject_bank_share_grants_target_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inject_bank_share_grants'))
    )
    op.create_index(op.f('ix_inject_bank_share_grants_created_by_user_id'), 'inject_bank_share_grants', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_inject_bank_share_grants_item_id'), 'inject_bank_share_grants', ['item_id'], unique=False)
    op.create_index(op.f('ix_inject_bank_share_grants_source_tenant_id'), 'inject_bank_share_grants', ['source_tenant_id'], unique=False)
    op.create_index(op.f('ix_inject_bank_share_grants_status'), 'inject_bank_share_grants', ['status'], unique=False)
    op.create_index('ix_inject_bank_share_grants_target_status', 'inject_bank_share_grants', ['target_tenant_id', 'status'], unique=False)
    op.create_index(op.f('ix_inject_bank_share_grants_target_tenant_id'), 'inject_bank_share_grants', ['target_tenant_id'], unique=False)
    op.create_table('media',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('exercise_id', sa.Integer(), nullable=True),
    sa.Column('owner_team_id', sa.Integer(), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('storage_provider', sa.Enum('LOCAL', 'S3', name='storageprovider'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tags', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('visibility', sa.Enum('PRIVATE', 'TEAM', 'EXERCISE', 'GLOBAL', name='mediavisibility'), nullable=False),
    sa.Column('status', sa.Enum('UPLOADING', 'PROCESSING', 'READY', 'FAILED', name='mediastatus'), nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], name=op.f('fk_media_exercise_id_exercises'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_team_id'], ['teams.id'], name=op.f('fk_media_owner_team_id_teams'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_media_tenant_id_tenants'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], name=op.f('fk_media_uploaded_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_media'))
    )
    op.create_index(op.f('ix_media_exercise_id'), 'media', ['exercise_id'], unique=False)
    op.create_index(op.f('ix_media_mime_type'), 'media', ['mime_type'], unique=False)
    op.create_index(op.f('ix_media_owner_team_id'), 'media', ['owner_team_id'], unique=False)
    op.create_index(op.f('ix_media_sha256'), 'media', ['sha256'], unique=False)
    op.create_index(op.f('ix_media_tenant_id'), 'media', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_media_uploaded_by'), 'media', ['uploaded_by'], unique=False)
    op.create_table('observer_notes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('observer_id', sa.Integer(), nullable=False),
    sa.Column('target_team_id', sa.Integer(), nullable=True),
    sa.Column('target_user_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('importance', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], name=op.f('fk_observer_notes_exercise_id_exercises'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['observer_id'], ['users.id'], name=op.f('fk_observer_notes_observer_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_team_id'], ['teams.id'], name=op.f('fk_observer_notes_target_team_id_teams'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['target_user_id'], ['users.id'], name=op.f('fk_observer_notes_target_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_observer_notes'))
    )
    op.create_index(op.f('ix_observer_notes_exercise_id'), 'observer_notes', ['exercise_id'], unique=False)
    op.create_index(op.f('ix_observer_notes_observer_id'), 'observer_notes', ['observer_id'], unique=False)
    op.create_table('retex_reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('generated_by', sa.Integer(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('kpis', sa.JSON(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], name=op.f('fk_retex_reports_exercise_id_exercises'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['generated_by'], ['users.id'], name=op.f('fk_retex_reports_generated_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_retex_reports'))
    )
    op.create_index(op.f('ix_retex_reports_exercise_id'), 'retex_reports', ['exercise_id'], unique=False)
    op.create_table('scores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('max_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('scored_by', sa.Integer(), nullable=False),
    sa.Column('scored_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], name=op.f('fk_scores_exercise_id_exercises'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scored_by'], ['users.id'], name=op.f('fk_scores_scored_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_scores_team_id_teams'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_scores_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scores'))
    )
    op.create_index(op.f('ix_scores_exercise_id'), 'scores', ['exercise_id'], unique=False)
    op.create_index(op.f('ix_scores_team_id'), 'scores', ['team_id'], unique=False)
    op.create_table('tv_channels',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('logo_url', sa.Text(), nullable=True),
    sa.Column('style_preset', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], name=op.f('fk_tv_channels_exercise_id_exercises'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tv_channels'))
    )
    op.create_index(op.f('ix_tv_channels_exercise_id'), 'tv_channels', ['exercise_id'], unique=False)
    op.create_table('twitter_accounts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('handle', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('account_type', sa.Enum('JOURNALIST', 'INFLUENCER', 'OFFICIAL', 'ANONYMOUS', 'TEAM_COMM', 'FAKE_NEWS', name='twitteraccounttype'), nullable=False),
    sa.Column('controlled_by_team_id', sa.Integer(), nullable=True),
    sa.Column('controlled_by_user_id', sa.Integer(), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['controlled_by_team_id'], ['teams.id'], name=op.f('fk_twitter_accounts_controlled_by_team_id_teams'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['controlled_by_user_id'], ['users.id'], name=op.f('fk_twitter_accounts_controlled_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], name=op.f('fk_twitter_accounts_exercise_id_exercises'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_twitter_accounts')),
    sa.UniqueConstraint('exercise_id', 'handle', name='uq_twitter_accounts_exercise_handle')
    )
    op.create_index(op.f('ix_twitter_accounts_exercise_id'), 'twitter_accounts', ['exercise_id'], unique=False)
    op.create_table('ws_auth_tickets',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('scope', sa.Enum('EXERCISE_UPDATES', 'SIMULATED_CHANNELS', 'DEBUG_EVENTS', name='wsauthticketscope'), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], name=op.f('fk_ws_auth_tickets_session_id_sessions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_ws_auth_tickets_tenant_id_tenants'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_ws_auth_tickets_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ws_auth_tickets'))
    )
    op.create_index(op.f('ix_ws_auth_tickets_expires_at'), 'ws_auth_tickets', ['expires_at'], unique=False)
    op.create_index(op.f('ix_ws_auth_tickets_session_id'), 'ws_auth_tickets', ['session_id'], unique=False)
    op.create_index(op.f('ix_ws_auth_tickets_tenant_id'), 'ws_auth_tickets', ['tenant_id'], unique=False)
    op.create_index('ix_ws_auth_tickets_tenant_scope_expires', 'ws_auth_tickets', ['tenant_id', 'scope', 'expires_at'], unique=False)
    op.create_index('ix_ws_auth_tickets_user_expires', 'ws_auth_tickets', ['user_id', 'expires_at'], unique=False)
    op.create_index(op.f('ix_ws_auth_tickets_user_id'), 'ws_auth_tickets', ['user_id'], unique=False)
    op.create_table('event_audiences',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('ROLE', 'TEAM', 'USER', 'TAG', name='audiencekind'), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_event_audiences_event_id_events'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_event_audiences'))
    )
    op.create_index(op.f('ix_event_audiences_event_id'), 'event_audiences', ['event_id'], unique=False)
    op.create_table('injects',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('phase_id', sa.Integer(), nullable=True),
    sa.Column('custom_id', sa.String(length=50), nullable=True),
    sa.Column('type', sa.Enum('mail', 'twitter', 'tv', 'decision', 'score', 'system', name='inject_type'), nullable=False),
    sa.Column('timeline_type', sa.Enum('business', 'technical', name='timelinetype'), server_default='business', nullable=False),
    sa.Column('is_surprise', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('inject_category', sa.Enum('information', 'incident', 'decision', 'media', 'technical', 'legal', 'canal_press', 'canal_anssi', 'canal_gouvernement', name='injectcategory'), nullable=True),
    sa.Column('channel', sa.Enum('mail', 'phone', 'press', 'siem', 'tv', 'social_network', 'official_mail', name='injectchannel'), nullable=True),
    sa.Column('data_format', sa.String(length=16), server_default='text', nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('time_offset', sa.Integer(), nullable=True),
    sa.Column('duration_min', sa.Integer(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('draft', 'scheduled', 'sent', 'cancelled', name='inject_status'), nullable=False),
    sa.Column('target_audience', sa.Enum('direction', 'dsi', 'com', 'legal', 'care', 'all', name='targetaudience'), nullable=True),
    sa.Column('pedagogical_objective', sa.Text(), nullable=True),
    sa.Column('tested_competence', sa.Enum('coordination', 'arbitration', 'communication', 'technical', 'governance', name='testedcompetence'), nullable=True),
    sa.Column('pressure_level', sa.Enum('low', 'medium', 'high', 'critical', name='pressurelevel'), nullable=True),
    sa.Column('dependency_ids', sa.JSON(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_injects_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], name=op.f('fk_injects_exercise_id_exercises'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['phase_id'], ['exercise_phases.id'], name=op.f('fk_injects_phase_id_exercise_phases'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_injects'))
    )
    op.create_index(op.f('ix_injects_custom_id'), 'injects', ['custom_id'], unique=False)
    op.create_index(op.f('ix_injects_exercise_id'), 'injects', ['exercise_id'], unique=False)
    op.create_index(op.f('ix_injects_phase_id'), 'injects', ['phase_id'], unique=False)
    op.create_index(op.f('ix_injects_scheduled_at'), 'injects', ['scheduled_at'], unique=False)
    op.create_table('media_renditions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=50), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['media.id'], name=op.f('fk_media_renditions_asset_id_media'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_media_renditions'))
    )
    op.create_index(op.f('ix_media_renditions_asset_id'), 'media_renditions', ['asset_id'], unique=False)
    op.create_table('participant_capabilities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('exercise_user_id', sa.Integer(), nullable=False),
    sa.Column('can_social', sa.Boolean(), nullable=False),
    sa.Column('can_tv', sa.Boolean(), nullable=False),
    sa.Column('can_mail', sa.Boolean(), nullable=False),
    sa.Column('visibility_scope', sa.Enum('TEAM_ONLY', 'USER_ONLY', 'ALL', name='injectvisibilityscope'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], name=op.f('fk_participant_capabilities_exercise_id_exercises'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['exercise_user_id'], ['exercise_users.id'], name=op.f('fk_participant_capabilities_exercise_user_id_exercise_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_participant_capabilities')),
    sa.UniqueConstraint('exercise_user_id', name='uq_participant_capability_user')
    )
    op.create_index(op.f('ix_participant_capabilities_exercise_id'), 'participant_capabilities', ['exercise_id'], unique=False)
    op.create_index(op.f('ix_participant_capabilities_exercise_user_id'), 'participant_capabilities', ['exercise_user_id'], unique=False)
    op.create_table('tv_live_state',
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('IDLE', 'PLAYING', 'PAUSED', 'ENDED', name='tvlivestatus'), nullable=False),
    sa.Column('on_air_type', sa.String(length=20), nullable=True),
    sa.Column('on_air_id', sa.Integer(), nullable=True),
    sa.Column('on_air_media_id', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('banner_text', sa.Text(), nullable=True),
    sa.Column('ticker_items', sa.JSON(), nullable=False),
    sa.Column('version', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['tv_channels.id'], name=op.f('fk_tv_live_state_channel_id_tv_channels'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['on_air_media_id'], ['media.id'], name=op.f('fk_tv_live_state_on_air_media_id_media'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('channel_id', name=op.f('pk_tv_live_state'))
    )
    op.create_table('tv_playlist_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('item_type', sa.String(length=30), nullable=False),
    sa.Column('ref_id', sa.Integer(), nullable=True),
    sa.Column('media_id', sa.Integer(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('planned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('QUEUED', 'ON_AIR', 'DONE', 'SKIPPED', name='playlistitemstatus'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('banner_text', sa.Text(), nullable=True),
    sa.Column('ticker_items', sa.JSON(), nullable=True),
    sa.Column('play_mode', sa.String(length=20), nullable=True),
    sa.Column('takeover', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['tv_channels.id'], name=op.f('fk_tv_playlist_items_channel_id_tv_channels'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], name=op.f('fk_tv_playlist_items_exercise_id_exercises'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], name=op.f('fk_tv_playlist_items_media_id_media'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tv_playlist_items'))
    )
    op.create_index(op.f('ix_tv_playlist_items_channel_id'), 'tv_playlist_items', ['channel_id'], unique=False)
    op.create_index(op.f('ix_tv_playlist_items_exercise_id'), 'tv_playlist_items', ['exercise_id'], unique=False)
    op.create_table('twitter_posts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('post_type', sa.Enum('TWEET', 'REPLY', 'QUOTE', 'RETWEET', name='twitterposttype'), nullable=False),
    sa.Column('parent_post_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['twitter_accounts.id'], name=op.f('fk_twitter_posts_account_id_twitter_accounts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], name=op.f('fk_twitter_posts_exercise_id_exercises'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_post_id'], ['twitter_posts.id'], name=op.f('fk_twitter_posts_parent_post_id_twitter_posts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_twitter_posts'))
    )
    op.create_index(op.f('ix_twitter_posts_account_id'), 'twitter_posts', ['account_id'], unique=False)
    op.create_index(op.f('ix_twitter_posts_created_at'), 'twitter_posts', ['created_at'], unique=False)
    op.create_index(op.f('ix_twitter_posts_exercise_id'), 'twitter_posts', ['exercise_id'], unique=False)
    op.create_index(op.f('ix_twitter_posts_parent_post_id'), 'twitter_posts', ['parent_post_id'], unique=False)
    op.create_table('chat_rooms',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('room_type', sa.Enum('PUBLIC', 'TEAM', 'INJECT', 'DIRECT', name='chatroomtype'), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('inject_id', sa.Integer(), nullable=True),
    sa.Column('participant_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_chat_rooms_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], name=op.f('fk_chat_rooms_exercise_id_exercises'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['inject_id'], ['injects.id'], name=op.f('fk_chat_rooms_inject_id_injects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_chat_rooms_team_id_teams'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chat_rooms'))
    )
    op.create_index('ix_chat_rooms_exercise_id', 'chat_rooms', ['exercise_id'], unique=False)
    op.create_index('ix_chat_rooms_team_id', 'chat_rooms', ['team_id'], unique=False)
    op.create_table('conversations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=False),
    sa.Column('inject_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], name=op.f('fk_conversations_exercise_id_exercises'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['inject_id'], ['injects.id'], name=op.f('fk_conversations_inject_id_injects'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversations'))
    )
    op.create_index(op.f('ix_conversations_exercise_id'), 'conversations', ['exercise_id'], unique=False)
    op.create_table('deliveries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('inject_id', sa.Integer(), nullable=False),
    sa.Column('target_user_id', sa.Integer(), nullable=True),
    sa.Column('target_team_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'delivered', 'opened', 'acknowledged', 'in_progress', 'treated', 'replied', name='delivery_status'), nullable=False),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('treated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('treated_by', sa.Integer(), nullable=True),
    sa.Column('first_reply_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['inject_id'], ['injects.id'], name=op.f('fk_deliveries_inject_id_injects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_team_id'], ['teams.id'], name=op.f('fk_deliveries_target_team_id_teams'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_user_id'], ['users.id'], name=op.f('fk_deliveries_target_user_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['treated_by'], ['users.id'], name=op.f('fk_deliveries_treated_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_deliveries'))
    )
    op.create_index(op.f('ix_deliveries_inject_id'), 'deliveries', ['inject_id'], unique=False)
    op.create_index(op.f('ix_deliveries_target_team_id'), 'deliveries', ['target_team_id'], unique=False)
    op.create_index(op.f('ix_deliveries_target_user_id'), 'deliveries', ['target_user_id'], unique=False)
    op.create_table('inject_audiences',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('inject_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('ROLE', 'TEAM', 'USER', 'TAG', name='audiencekind'), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['inject_id'], ['injects.id'], name=op.f('fk_inject_audiences_inject_id_injects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inject_audiences'))
    )
    op.create_index(op.f('ix_inject_audiences_inject_id'), 'inject_audiences', ['inject_id'], unique=False)
    op.create_table('inject_media',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('inject_id', sa.Integer(), nullable=False),
    sa.Column('media_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['inject_id'], ['injects.id'], name=op.f('fk_inject_media_inject_id_injects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], name=op.f('fk_inject_media_media_id_media'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inject_media'))
    )
    op.create_index(op.f('ix_inject_media_inject_id'), 'inject_media', ['inject_id'], unique=False)
    op.create_index(op.f('ix_inject_media_media_id'), 'inject_media', ['media_id'], unique=False)
    op.create_table('inject_trigger_rules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('inject_id', sa.Integer(), nullable=False),
    sa.Column('trigger_mode', sa.Enum('AUTO', 'MANUAL', 'CONDITIONAL', name='triggermode'), nullable=False),
    sa.Column('expression', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], name=op.f('fk_inject_trigger_rules_exercise_id_exercises'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['inject_id'], ['injects.id'], name=op.f('fk_inject_trigger_rules_inject_id_injects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inject_trigger_rules')),
    sa.UniqueConstraint('inject_id', name='uq_inject_trigger_rule')
    )
    op.create_index(op.f('ix_inject_trigger_rules_exercise_id'), 'inject_trigger_rules', ['exercise_id'], unique=False)
    op.create_index(op.f('ix_inject_trigger_rules_inject_id'), 'inject_trigger_rules', ['inject_id'], unique=False)
    op.create_table('tv_segments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('segment_type', sa.Enum('BREAKING', 'NEWS', 'INTERVIEW', 'REPORT', 'TICKER', 'COMMERCIAL', name='tvsegmenttype'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('banner_text', sa.Text(), nullable=True),
    sa.Column('ticker_text', sa.Text(), nullable=True),
    sa.Column('script', sa.Text(), nullable=True),
    sa.Column('inject_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('PREPARED', 'LIVE', 'ENDED', name='tvsegmentstatus'), nullable=False),
    sa.Column('scheduled_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scheduled_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['tv_channels.id'], name=op.f('fk_tv_segments_channel_id_tv_channels'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_tv_segments_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['inject_id'], ['injects.id'], name=op.f('fk_tv_segments_inject_id_injects'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tv_segments'))
    )
    op.create_index(op.f('ix_tv_segments_channel_id'), 'tv_segments', ['channel_id'], unique=False)
    op.create_table('twitter_post_media',
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('media_id', sa.Integer(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], name=op.f('fk_twitter_post_media_media_id_media'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['twitter_posts.id'], name=op.f('fk_twitter_post_media_post_id_twitter_posts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('post_id', 'media_id', name=op.f('pk_twitter_post_media'))
    )
    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('author_type', sa.String(length=20), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('author_label', sa.String(length=100), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('parent_message_id', sa.Integer(), nullable=True),
    sa.Column('is_pinned', sa.Boolean(), nullable=False),
    sa.Column('pinned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pinned_by', sa.Integer(), nullable=True),
    sa.Column('reactions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_chat_messages_author_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_message_id'], ['chat_messages.id'], name=op.f('fk_chat_messages_parent_message_id_chat_messages'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['pinned_by'], ['users.id'], name=op.f('fk_chat_messages_pinned_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['room_id'], ['chat_rooms.id'], name=op.f('fk_chat_messages_room_id_chat_rooms'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chat_messages'))
    )
    op.create_index('ix_chat_messages_created_at', 'chat_messages', ['created_at'], unique=False)
    op.create_index('ix_chat_messages_room_id', 'chat_messages', ['room_id'], unique=False)
    op.create_table('conversation_participants',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('participant_type', sa.String(length=10), nullable=False),
    sa.Column('participant_id', sa.Integer(), nullable=True),
    sa.Column('participant_label', sa.String(length=100), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('fk_conversation_participants_conversation_id_conversations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversation_participants'))
    )
    op.create_index(op.f('ix_conversation_participants_conversation_id'), 'conversation_participants', ['conversation_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('parent_message_id', sa.Integer(), nullable=True),
    sa.Column('author_type', sa.Enum('USER', 'ACTOR', 'SYSTEM', name='authortype'), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('author_label', sa.String(length=100), nullable=True),
    sa.Column('subject', sa.String(length=500), nullable=True),
    sa.Column('body_text', sa.Text(), nullable=False),
    sa.Column('body_html', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_messages_author_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('fk_messages_conversation_id_conversations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_message_id'], ['messages.id'], name=op.f('fk_messages_parent_message_id_messages'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_messages'))
    )
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_messages_created_at'), 'messages', ['created_at'], unique=False)
    op.create_table('tv_segment_media',
    sa.Column('segment_id', sa.Integer(), nullable=False),
    sa.Column('media_id', sa.Integer(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('media_type', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], name=op.f('fk_tv_segment_media_media_id_media'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['segment_id'], ['tv_segments.id'], name=op.f('fk_tv_segment_media_segment_id_tv_segments'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('segment_id', 'media_id', name=op.f('pk_tv_segment_media'))
    )
    op.create_table('chat_read_receipts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('last_read_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_read_message_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['last_read_message_id'], ['chat_messages.id'], name=op.f('fk_chat_read_receipts_last_read_message_id_chat_messages'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['room_id'], ['chat_rooms.id'], name=op.f('fk_chat_read_receipts_room_id_chat_rooms'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_chat_read_receipts_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chat_read_receipts')),
    sa.UniqueConstraint('room_id', 'user_id', name='uq_chat_read_receipts_room_user')
    )
    op.create_index('ix_chat_read_receipts_room_user', 'chat_read_receipts', ['room_id', 'user_id'], unique=False)
    op.create_table('message_attachments',
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('media_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], name=op.f('fk_message_attachments_media_id_media'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], name=op.f('fk_message_attachments_message_id_messages'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('message_id', 'media_id', name=op.f('pk_message_attachments'))
    )
    op.create_table('read_receipts',
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], name=op.f('fk_read_receipts_message_id_messages'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_read_receipts_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('message_id', 'user_id', name=op.f('pk_read_receipts'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('read_receipts')
    op.drop_table('message_attachments')
    op.drop_index('ix_chat_read_receipts_room_user', table_name='chat_read_receipts')
    op.drop_table('chat_read_receipts')
    op.drop_table('tv_segment_media')
    op.drop_index(op.f('ix_messages_created_at'), table_name='messages')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_conversation_participants_conversation_id'), table_name='conversation_participants')
    op.drop_table('conversation_participants')
    op.drop_index('ix_chat_messages_room_id', table_name='chat_messages')
    op.drop_index('ix_chat_messages_created_at', table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_table('twitter_post_media')
    op.drop_index(op.f('ix_tv_segments_channel_id'), table_name='tv_segments')
    op.drop_table('tv_segments')
    op.drop_index(op.f('ix_inject_trigger_rules_inject_id'), table_name='inject_trigger_rules')
    op.drop_index(op.f('ix_inject_trigger_rules_exercise_id'), table_name='inject_trigger_rules')
    op.drop_table('inject_trigger_rules')
    op.drop_index(op.f('ix_inject_media_media_id'), table_name='inject_media')
    op.drop_index(op.f('ix_inject_media_inject_id'), table_name='inject_media')
    op.drop_table('inject_media')
    op.drop_index(op.f('ix_inject_audiences_inject_id'), table_name='inject_audiences')
    op.drop_table('inject_audiences')
    op.drop_index(op.f('ix_deliveries_target_user_id'), table_name='deliveries')
    op.drop_index(op.f('ix_deliveries_target_team_id'), table_name='deliveries')
    op.drop_index(op.f('ix_deliveries_inject_id'), table_name='deliveries')
    op.drop_table('deliveries')
    op.drop_index(op.f('ix_conversations_exercise_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index('ix_chat_rooms_team_id', table_name='chat_rooms')
    op.drop_index('ix_chat_rooms_exercise_id', table_name='chat_rooms')
    op.drop_table('chat_rooms')
    op.drop_index(op.f('ix_twitter_posts_parent_post_id'), table_name='twitter_posts')
    op.drop_index(op.f('ix_twitter_posts_exercise_id'), table_name='twitter_posts')
    op.drop_index(op.f('ix_twitter_posts_created_at'), table_name='twitter_posts')
    op.drop_index(op.f('ix_twitter_posts_account_id'), table_name='twitter_posts')
    op.drop_table('twitter_posts')
    op.drop_index(op.f('ix_tv_playlist_items_exercise_id'), table_name='tv_playlist_items')
    op.drop_index(op.f('ix_tv_playlist_items_channel_id'), table_name='tv_playlist_items')
    op.drop_table('tv_playlist_items')
    op.drop_table('tv_live_state')
    op.drop_index(op.f('ix_participant_capabilities_exercise_user_id'), table_name='participant_capabilities')
    op.drop_index(op.f('ix_participant_capabilities_exercise_id'), table_name='participant_capabilities')
    op.drop_table('participant_capabilities')
    op.drop_index(op.f('ix_media_renditions_asset_id'), table_name='media_renditions')
    op.drop_table('media_renditions')
    op.drop_index(op.f('ix_injects_scheduled_at'), table_name='injects')
    op.drop_index(op.f('ix_injects_phase_id'), table_name='injects')
    op.drop_index(op.f('ix_injects_exercise_id'), table_name='injects')
    op.drop_index(op.f('ix_injects_custom_id'), table_name='injects')
    op.drop_table('injects')
    op.drop_index(op.f('ix_event_audiences_event_id'), table_name='event_audiences')
    op.drop_table('event_audiences')
    op.drop_index(op.f('ix_ws_auth_tickets_user_id'), table_name='ws_auth_tickets')
    op.drop_index('ix_ws_auth_tickets_user_expires', table_name='ws_auth_tickets')
    op.drop_index('ix_ws_auth_tickets_tenant_scope_expires', table_name='ws_auth_tickets')
    op.drop_index(op.f('ix_ws_auth_tickets_tenant_id'), table_name='ws_auth_tickets')
    op.drop_index(op.f('ix_ws_auth_tickets_session_id'), table_name='ws_auth_tickets')
    op.drop_index(op.f('ix_ws_auth_tickets_expires_at'), table_name='ws_auth_tickets')
    op.drop_table('ws_auth_tickets')
    op.drop_index(op.f('ix_twitter_accounts_exercise_id'), table_name='twitter_accounts')
    op.drop_table('twitter_accounts')
    op.drop_index(op.f('ix_tv_channels_exercise_id'), table_name='tv_channels')
    op.drop_table('tv_channels')
    op.drop_index(op.f('ix_scores_team_id'), table_name='scores')
    op.drop_index(op.f('ix_scores_exercise_id'), table_name='scores')
    op.drop_table('scores')
    op.drop_index(op.f('ix_retex_reports_exercise_id'), table_name='retex_reports')
    op.drop_table('retex_reports')
    op.drop_index(op.f('ix_observer_notes_observer_id'), table_name='observer_notes')
    op.drop_index(op.f('ix_observer_notes_exercise_id'), table_name='observer_notes')
    op.drop_table('observer_notes')
    op.drop_index(op.f('ix_media_uploaded_by'), table_name='media')
    op.drop_index(op.f('ix_media_tenant_id'), table_name='media')
    op.drop_index(op.f('ix_media_sha256'), table_name='media')
    op.drop_index(op.f('ix_media_owner_team_id'), table_name='media')
    op.drop_index(op.f('ix_media_mime_type'), table_name='media')
    op.drop_index(op.f('ix_media_exercise_id'), table_name='media')
    op.drop_table('media')
    op.drop_index(op.f('ix_inject_bank_share_grants_target_tenant_id'), table_name='inject_bank_share_grants')
    op.drop_index('ix_inject_bank_share_grants_target_status', table_name='inject_bank_share_grants')
    op.drop_index(op.f('ix_inject_bank_share_grants_status'), table_name='inject_bank_share_grants')
    op.drop_index(op.f('ix_inject_bank_share_grants_source_tenant_id'), table_name='inject_bank_share_grants')
    op.drop_index(op.f('ix_inject_bank_share_grants_item_id'), table_name='inject_bank_share_grants')
    op.drop_index(op.f('ix_inject_bank_share_grants_created_by_user_id'), table_name='inject_bank_share_grants')
    op.drop_table('inject_bank_share_grants')
    op.drop_index(op.f('ix_exercise_users_user_id'), table_name='exercise_users')
    op.drop_index(op.f('ix_exercise_users_exercise_id'), table_name='exercise_users')
    op.drop_table('exercise_users')
    op.drop_table('exercise_user_credentials')
    op.drop_table('exercise_teams')
    op.drop_index(op.f('ix_exercise_scenarios_exercise_id'), table_name='exercise_scenarios')
    op.drop_table('exercise_scenarios')
    op.drop_index(op.f('ix_exercise_plugins_exercise_id'), table_name='exercise_plugins')
    op.drop_table('exercise_plugins')
    op.drop_index(op.f('ix_exercise_phases_exercise_id'), table_name='exercise_phases')
    op.drop_table('exercise_phases')
    op.drop_index(op.f('ix_exercise_metric_snapshots_ts'), table_name='exercise_metric_snapshots')
    op.drop_index(op.f('ix_exercise_metric_snapshots_exercise_id'), table_name='exercise_metric_snapshots')
    op.drop_table('exercise_metric_snapshots')
    op.drop_index(op.f('ix_exercise_escalation_axes_exercise_id'), table_name='exercise_escalation_axes')
    op.drop_table('exercise_escalation_axes')
    op.drop_index(op.f('ix_events_ts'), table_name='events')
    op.drop_index('ix_events_exercise_ts', table_name='events')
    op.drop_index(op.f('ix_events_exercise_id'), table_name='events')
    op.drop_index('ix_events_entity', table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_decisions_team_id'), table_name='decisions')
    op.drop_index(op.f('ix_decisions_exercise_id'), table_name='decisions')
    op.drop_table('decisions')
    op.drop_index('ix_crisis_contacts_exercise_search', table_name='crisis_contacts')
    op.drop_index(op.f('ix_crisis_contacts_exercise_id'), table_name='crisis_contacts')
    op.drop_index('ix_crisis_contacts_category', table_name='crisis_contacts')
    op.drop_table('crisis_contacts')
    op.drop_table('welcome_kit_templates')
    op.drop_table('user_teams')
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_token_hash'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_tenant_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_expires_at'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_inject_bank_items_visibility_scope'), table_name='inject_bank_items')
    op.drop_index(op.f('ix_inject_bank_items_status'), table_name='inject_bank_items')
    op.drop_index(op.f('ix_inject_bank_items_source_type'), table_name='inject_bank_items')
    op.drop_index(op.f('ix_inject_bank_items_owner_tenant_id'), table_name='inject_bank_items')
    op.drop_index(op.f('ix_inject_bank_items_kind'), table_name='inject_bank_items')
    op.drop_index(op.f('ix_inject_bank_items_custom_id'), table_name='inject_bank_items')
    op.drop_index(op.f('ix_inject_bank_items_category'), table_name='inject_bank_items')
    op.drop_table('inject_bank_items')
    op.drop_index(op.f('ix_exercises_tenant_id'), table_name='exercises')
    op.drop_table('exercises')
    op.drop_index(op.f('ix_audit_log_user_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_tenant_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_created_at'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_action'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_index(op.f('ix_users_team_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tenant_plugin_configurations_tenant_id'), table_name='tenant_plugin_configurations')
    op.drop_table('tenant_plugin_configurations')
    op.drop_index(op.f('ix_tenant_domains_tenant_id'), table_name='tenant_domains')
    op.drop_table('tenant_domains')
    op.drop_index(op.f('ix_tenant_configurations_tenant_id'), table_name='tenant_configurations')
    op.drop_table('tenant_configurations')
    op.drop_index(op.f('ix_teams_tenant_id'), table_name='teams')
    op.drop_table('teams')
    op.drop_index(op.f('ix_tenants_slug'), table_name='tenants')
    op.drop_table('tenants')
    op.drop_table('plugin_configurations')
    op.drop_table('app_configurations')
    # ### end Alembic commands ###