export const DEFAULT_PHASES_LIST = [
  'Détection',
  'Qualification',
  'Alerte',
  'Activation de la cellule de crise',
  'Analyse de situation',
  'Décisions stratégiques',
  'Endiguement',
  "Continuité d'activité (mode dégradé)",
  'Communication interne',
  'Communication externe (autorités, médias, partenaires)',
  'Remédiation technique',
  'Clôture de crise',
  "RETEX (retour d'expérience)",
  "Plan d'actions correctives",
]

export const PHASE_PRESETS = {
  minimal: [
    'Détection',
    'Activation de la cellule de crise',
    'Remédiation technique',
    'Clôture de crise',
  ],
  classique: [
    'Détection',
    'Qualification',
    'Alerte',
    'Activation de la cellule de crise',
    'Analyse de situation',
    'Décisions stratégiques',
    'Endiguement',
    'Remédiation technique',
    'Clôture de crise',
  ],
  precis: [
    'Détection',
    'Qualification',
    'Alerte',
    'Activation de la cellule de crise',
    'Analyse de situation',
    'Décisions stratégiques',
    'Endiguement',
    "Continuité d'activité (mode dégradé)",
    'Communication interne',
    'Communication externe (autorités, médias, partenaires)',
    'Remédiation technique',
    'Clôture de crise',
    "RETEX (retour d'expérience)",
  ],
  full: [...DEFAULT_PHASES_LIST],
}

export type PhasePresetKey = keyof typeof PHASE_PRESETS

export const PHASE_PRESET_LABELS: Record<PhasePresetKey, string> = {
  minimal: 'Minimal',
  classique: 'Classique',
  precis: 'Précis',
  full: 'Complet',
}

export const PHASE_COLOR_PALETTE = [
  '#ef4444',
  '#f97316',
  '#f59e0b',
  '#84cc16',
  '#10b981',
  '#14b8a6',
  '#0ea5e9',
  '#6366f1',
  '#a855f7',
  '#ec4899',
]

export const PHASE_PRESET_DEFAULT_DURATIONS: Record<PhasePresetKey, Record<string, number>> = {
  minimal: {
    'Détection': 20,
    'Activation de la cellule de crise': 30,
    'Remédiation technique': 40,
    'Clôture de crise': 10,
  },
  classique: {
    'Détection': 30,
    'Qualification': 20,
    'Alerte': 20,
    'Activation de la cellule de crise': 30,
    'Analyse de situation': 25,
    'Décisions stratégiques': 15,
    'Endiguement': 25,
    'Remédiation technique': 30,
    'Clôture de crise': 10,
  },
  precis: {
    'Détection': 25,
    'Qualification': 25,
    'Alerte': 20,
    'Activation de la cellule de crise': 30,
    'Analyse de situation': 25,
    'Décisions stratégiques': 15,
    'Endiguement': 25,
    "Continuité d'activité (mode dégradé)": 20,
    'Communication interne': 20,
    'Communication externe (autorités, médias, partenaires)': 20,
    'Remédiation technique': 30,
    'Clôture de crise': 10,
    "RETEX (retour d'expérience)": 10,
  },
  full: {
    'Détection': 25,
    'Qualification': 25,
    'Alerte': 20,
    'Activation de la cellule de crise': 30,
    'Analyse de situation': 25,
    'Décisions stratégiques': 20,
    'Endiguement': 25,
    "Continuité d'activité (mode dégradé)": 25,
    'Communication interne': 20,
    'Communication externe (autorités, médias, partenaires)': 20,
    'Remédiation technique': 30,
    'Clôture de crise': 15,
    "RETEX (retour d'expérience)": 15,
    "Plan d'actions correctives": 10,
  },
}
